package com.example.saxonheritage.services;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.ws.Action;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-05-01T17:26:46.204+01:00
 * Generated source version: 4.0.0
 *
 */
@WebService(targetNamespace = "http://services.saxonheritage.example.com/", name = "MemberService")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface MemberService {

    @WebMethod
    @Action(input = "http://services.saxonheritage.example.com/MemberService/getMembershipInfoRequest", output = "http://services.saxonheritage.example.com/MemberService/getMembershipInfoResponse")
    @WebResult(name = "return", targetNamespace = "http://services.saxonheritage.example.com/", partName = "return")
    public java.lang.String getMembershipInfo(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://services.saxonheritage.example.com/MemberService/registerMemberRequest", output = "http://services.saxonheritage.example.com/MemberService/registerMemberResponse")
    @WebResult(name = "return", targetNamespace = "http://services.saxonheritage.example.com/", partName = "return")
    public java.lang.String registerMember(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://services.saxonheritage.example.com/MemberService/sendPromotionRequest", output = "http://services.saxonheritage.example.com/MemberService/sendPromotionResponse")
    public void sendPromotion(

        @WebParam(partName = "arg0", name = "arg0")
        int arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://services.saxonheritage.example.com/MemberService/updateMemberDetailsRequest", output = "http://services.saxonheritage.example.com/MemberService/updateMemberDetailsResponse")
    @WebResult(name = "return", targetNamespace = "http://services.saxonheritage.example.com/", partName = "return")
    public java.lang.String updateMemberDetails(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://services.saxonheritage.example.com/MemberService/submitVisitorReportRequest", output = "http://services.saxonheritage.example.com/MemberService/submitVisitorReportResponse")
    public void submitVisitorReport(

        @WebParam(partName = "arg0", name = "arg0")
        int arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1
    );
}
