package com.example.saxonheritage.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-05-01T17:26:46.257+01:00
 * Generated source version: 4.0.0
 *
 */
@WebServiceClient(name = "MemberServiceImplService",
                  wsdlLocation = "file:/C:/Users/Agnijus/IdeaProjects/SaxonHeritage/src/main/resources/wsdl/memberService.wsdl.xml",
                  targetNamespace = "http://services.saxonheritage.example.com/")
public class MemberServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.saxonheritage.example.com/", "MemberServiceImplService");
    public final static QName MemberServiceImplPort = new QName("http://services.saxonheritage.example.com/", "MemberServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Agnijus/IdeaProjects/SaxonHeritage/src/main/resources/wsdl/memberService.wsdl.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MemberServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Agnijus/IdeaProjects/SaxonHeritage/src/main/resources/wsdl/memberService.wsdl.xml");
        }
        WSDL_LOCATION = url;
    }

    public MemberServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MemberServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MemberServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public MemberServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MemberServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MemberServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns MemberService
     */
    @WebEndpoint(name = "MemberServiceImplPort")
    public MemberService getMemberServiceImplPort() {
        return super.getPort(MemberServiceImplPort, MemberService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MemberService
     */
    @WebEndpoint(name = "MemberServiceImplPort")
    public MemberService getMemberServiceImplPort(WebServiceFeature... features) {
        return super.getPort(MemberServiceImplPort, MemberService.class, features);
    }

}
